### PR TITLE
Python3 compatible

### PR DESCRIPTION
**Pull request by jakobsn**
Made small changes to run with python3

### CODE REVIEW

**Review by grahammitchell — CHANGES_REQUESTED** [review]
Thanks for the PR!

- The `print()` change is fine; it works out of the box on Python 2.7 and Python 3.
- The removal of `org()` is unnecessary; although it isn't needed on Python 3 it's not harmful either.
- However, the change from `items()` to `iteritems()` is problematic.

This file is intended to be executable out-of-the-box on MacOS and Linux, and unless I'm mistaken `/usr/bin/python` is still Python 2.7 on both of these systems.

If you can come up with a clean solution that works on both Python 2.7 and Python 3 I'd be happy to merge the PR.

**Comment by grahammitchell** [comment]
You've also reminded me that I should add a `CONTRIBUTING.md` that clarifies that I expect this file to be executable and correct out of the box on MacOS and Linux systems, since there's no way you could have known that other than the shebang line at the top.

**Comment by jakobsn** [comment]
Thanks for your feedback, I have altered the code to support both python 2 and 3:

The org() function had to be removed to be compatible with python3 because 'h' is a bytes object in python2, while it is an bytearray in python3. By casting the hash digest to bytearray, python2 does not require org() either.

I can see the problem with changing iteritems(), since it returns a list, while items() returns a view. Since iteritems is deprecated in python3 I chose to cast the list type on the view object.

**Comment by grahammitchell** [comment]
Looks great. I swear I had checked that in Python 3 `ord()` on a `byte` was a no-op but you're right that it throws a type error.

**Pull request merged**
